2022-10-03 13:57:00,570 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 71, in uninUtilDirn
    intc['tredBitsRecdMax'] = getTredMax(intc['itemIDBitsRecd'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 415, in getTredMax
    tred = round(max(listTred) / 10**9, 3)
ValueError: max() arg is an empty sequence
2022-11-28 16:16:43,841 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-11-28 16:17:15,249 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
